### Create a new user
POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
  "firstname": "hamid",
  "lastname": "bahmanyar",
  "email": "hamid@gmail.com",
  "password": "asdf",
  "password_confirm": "asdf"
}

### Sign in as an existing user
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
  "email": "amin@gmail.com",
  "password": "asdf"
}

### Get the currently signed is user
GET http://localhost:4000/api/auth/whoami

### Sign out
POST http://localhost:4000/api/auth/signout