### Create a new board
POST http://localhost:4000/api/boards
Content-Type: application/json

{
  "title": "Movies",
  "is_private": false
}

### Retrieve a board
GET http://localhost:4000/api/boards/7feffe2d-4976-4d9d-96fe-c70460995fde

### Get all boards of a user
GET http://localhost:4000/api/boards

### Update a board
PATCH http://localhost:4000/api/boards/7feffe2d-4976-4d9d-96fe-c70460995fde
Content-Type: : application/json

{
  "title": "Software Engineering",
  "is_private": true
}

### Delete a board
DELETE http://localhost:4000/api/boards/8a97b8d0-1350-40f5-8bf3-d37aa744e635

### Join a board
POST http://localhost:4000/api/boards/join/8a97b8d0-1350-40f5-8bf3-d37aa744e635

### leave a board
DELETE http://localhost:4000/api/boards/join/dcdc5999-a2dc-462e-bf1c-63d58b535ac9

### Create a new list
POST http://localhost:4000/api/boards/lists
Content-Type: application/json

{
  "title": "Projects2",
  "board_id": "8a97b8d0-1350-40f5-8bf3-d37aa744e635"
}

### Update a list
PATCH http://localhost:4000/api/boards/lists/7feffe2d-4976-4d9d-96fe-c70460995fde
Content-Type: : application/json

{
  "title": "Projects"
}

### delete a list
DELETE http://localhost:4000/api/boards/lists/68fe2adc-86c0-4e92-b0e2-952d5b4f584b