### Create a new board
POST http://localhost:4000/api/boards
Content-Type: application/json

{
  "title": "University",
  "is_private": true
}

### Retrieve a board
GET http://localhost:4000/api/boards/5ecc5ac7-b262-4739-9c0f-a902fbbf1b63

### Get all boards created by a user
GET http://localhost:4000/api/boards/created

### Get all boards a user joined
GET http://localhost:4000/api/boards/joined

### Get all public boards created by a users friends
GET http://localhost:4000/api/boards/suggested

### Update a board
PATCH http://localhost:4000/api/boards/7d78ded1-c2dd-4c32-9521-3ef88346de49
Content-Type: application/json

{
  "title": "University",
  "is_private": true
}

### Delete a board
DELETE http://localhost:4000/api/boards/8a97b8d0-1350-40f5-8bf3-d37aa744e635

### Join a board
POST http://localhost:4000/api/boards/join/bccf6bdf-1467-4543-9926-96913537ddbb

### leave a board
DELETE http://localhost:4000/api/boards/leave/564475a8-6357-4bcc-99fb-a50f06046324

### Create a new list
POST http://localhost:4000/api/boards/lists
Content-Type: application/json

{
  "title": "Homeworkes",
  "board_id": "7d78ded1-c2dd-4c32-9521-3ef88346de49"
}

### Update a list
PATCH http://localhost:4000/api/boards/lists/7feffe2d-4976-4d9d-96fe-c70460995fde
Content-Type: : application/json

{
  "title": "Projects"
}

### delete a list
DELETE http://localhost:4000/api/boards/lists/68fe2adc-86c0-4e92-b0e2-952d5b4f584b