### Create a new card
POST http://localhost:3000/api/cards
Content-Type: application/json

{
  "title": "Software Engineering",
  "list_id": "a12d94d2-252a-4bec-9412-a95977c13043",
  "due_date_time": "Wed, 21 Oct 2015 18:27:50 GMT"
}