### Update user info
PATCH http://localhost:3000/api/users
Content-Type: application/json

{
  "firstname": "bkjb",
  "lastname": "jbig"
}

### Add friendship status
POST http://localhost:4000/api/users/firends
Content-Type: application/json

{
  "user_id": "7d6e6806-76f4-4ded-81df-b7ea4d7b8831",
  "status": 0
}

### Get all friends
GET http://localhost:3000/api/users/firends

### Get all friend reqeusts
GET http://localhost:3000/api/users/firends/requests