### Update user info
PATCH http://localhost:4000/api/users
Content-Type: application/json

{
  "firstname": "",
  "lastname": "naemi"
}

### Change password
PATCH  http://localhost:4000/api/users/changePassword
Content-Type: application/json

{
  "current_password": "omid",
  "new_password": "ytdid",
  "new_password_confirm": "ytdid"
}

### Find a user with email
GET http://localhost:4000/api/users?email=omid@gmail.com

### Add friendship status
POST http://localhost:4000/api/users/firends
Content-Type: application/json

{
  "user_id": "250ed542-e613-4f31-81c8-aa018405779e",
  "status": 1
}

### Get all friends
GET http://localhost:3000/api/users/firends

### Get all friend reqeusts
GET http://localhost:3000/api/users/firends/requests